### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by nevze** [MRHRTZ/Tiktok-Scraper-Without-Watermark#11]
![Screenshot_20230108-232044066](https://user-images.githubusercontent.com/119541699/211207533-34db117d-f2e7-407f-a1fb-3aa6f3702913.jpg)

**Comment by MRHRTZ** [comment]
Can you send package.json in your project? Which version you install that, for testing see README.md first.

**Comment by nevze** [comment]
already fixed, thankyou
