### ISSUE TITLE
Error in Electron.

### ISSUE THREAD

**Issue by MaximFedarau** [MRHRTZ/Tiktok-Scraper-Without-Watermark#2]
Hi!. I use your library in my electron app. Everything works perfectly in simple terminal, but electron has these error:
"Cannot read properties of undefined (reading 'join')".
By the way it has the error: 
Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute

**Comment by MRHRTZ** [comment]
> Hi!. I use your library in my electron app. Everything works perfectly in simple terminal, but electron has these error: "Cannot read properties of undefined (reading 'join')". By the way it has the error: Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute

Hi thanks for report this issue, can you send full error or screenshot of that bug.

**Comment by MaximFedarau** [comment]
Hi! I have already solved this issue. I just used child_process and exec.
