### ISSUE TITLE
Can't download audio

### ISSUE THREAD

**Issue by xaliazhar** [MRHRTZ/Tiktok-Scraper-Without-Watermark#3]
Hi, thanks for making this library.

i have problem when using download url for audio. all urls work except audio.
no download action it just open ttdownloader.com site without sending me .mp3 file
![image](https://user-images.githubusercontent.com/58647884/159001788-5750fa6a-56b3-4b45-81ca-404ce6de3feb.png)
![image](https://user-images.githubusercontent.com/58647884/159001825-daca772a-022c-40cf-96da-6d8526ef21be.png)

**Comment by MRHRTZ** [comment]
for now use the latest function #7 , if audio doesn't work, use ffmpeg to convert it to mp3.
