### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by kotsh23** [MRHRTZ/Tiktok-Scraper-Without-Watermark#5]
C:\Users\Administrator\Desktop\videos-app-backend\node_modules\tiktok-scraper-without-watermark\src\function\index.js:20nction\index.js:209
                    nowm: $('#results-list > div:nth-child(2) > div.download > a')?.attr('href'),
                                                                                   ^

SyntaxError: Unexpected token '.'

**Comment by MRHRTZ** [comment]
Hi, that syntaxError because of you're using old version of nodejs, please update to stable or latest version, thanks.

**Comment by MRHRTZ** [comment]
Better use nodejs v14.x or latest
