### ISSUE TITLE
tested in codestandbox not working

### ISSUE THREAD

**Issue by sagarjaid** [MRHRTZ/Tiktok-Scraper-Without-Watermark#9]
https://codesandbox.io/s/peaceful-hellman-2jnke2?file=/app.js

**Comment by MRHRTZ** [comment]
For now add library from github directly, for project install like this
`npm install https://github.com/MRHRTZ/Tiktok-Scraper-Without-Watermark`


And for express example it can be like this
```
const express = require("express");
const tiktok = require("tiktok-scraper-without-watermark");

var app = express();

app.use(express.json());
app.use(express.urlencoded({ extended: false }));

app.get("/", (req, res) => {
  tiktok
    .tiktokdownload(req.query.url)
    .then((result) => {
      res.send(result)
    })
    .catch((e) => res.send(e));
});

var listener = app.listen(8080, function () {
  console.log("Listening on port " + listener.address().port);
});
```


then put the url on your browser
`http://localhost:8080/?url=https://www.tiktok.com/@fan_duet_vip/video/7136947095919054126?`

 ![API Result](https://i.ibb.co/pKpY5nM/result-tiktokdownload.png)
